# Copyright 2021 Manna Harbour
# https://github.com/manna-harbour/miryoku

name: 'Build All'
on:
  - workflow_dispatch
jobs:
  build:
    if: github.repository_owner == 'manna-harbour'
    uses: manna-harbour/miryoku_kmonad/.github/workflows/main.yml@main
    with:
      mode: '["build"]'
      alphas: '["default","azerty","colemak","colemakdhk","dvorak","halmak","workman","qwerty","qwertz"]'
      nav: '["default","vi","invertedt"]'
      clipboard: '["default","fun","mac","win"]'
      layers: '["default","flip"]'
      mapping: '["default","noreverseangle","lite"]'
      kmonad_os: '["default","mac","win"]'
