# Copyright 2021 Manna Harbour
# https://github.com/manna-harbour/miryoku

name: 'Build Tmk'
on:
  - workflow_dispatch
jobs:
  build:
    if: github.repository_owner == 'manna-harbour'
    uses: manna-harbour/miryoku_kmonad/.github/workflows/main.yml@main
    with:
      mode: '["build"]'
